spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/blogSearch
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false

#HOST
kakaoSearch: http://dapi.kakao.com

#REST API KEY
restApiKey: dfc7bd188adc3b82d9794404f9991b35