spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/blogSearch
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false

#HOST
kakaoSearchHost: http://dapi.kakao.com
naverSearchHost: https://openapi.naver.com

#REST API KEY
restApiKey: dfc7bd188adc3b82d9794404f9991b35
XNaverClientId: JLwJ_D31_2eHw4zKQHrq
XNaverClientSecret: xvItGlvhyg

#retryMax
retryMax: 10